### ISSUE TITLE
у меня баг

### ISSUE THREAD

**Issue by tailsjs** [evaqum/flutter-shopping-list#2]
почему когда еш кириешки со вкусом бекона то вылетает приложение не могу нормально пользоваться и есть кириешки с вкусом бекона одновременно!!!

**Comment by evaqum** [comment]
замените кириешки со вкусом бекона на три корочки со вкусом семги с сыром

**Comment by tailsjs** [comment]
здравствуйте три корочки какашка, а я ем только кириешки!!!

**Comment by evaqum** [comment]
замените кириешки со вкусом бекона на три корочки со вкусом кириешек со вкусом бекона

**Comment by tailsjs** [comment]
я попробовал в итоге какаято блеванина
